# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cperson.proto\"Q\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t\"$\n\nPersonList\x12\x16\n\x05items\x18\x01 \x03(\x0b\x32\x07.Person\"\x07\n\x05\x45mpty\"R\n\x13\x43reatePersonRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x03 \x01(\t\"\x1e\n\x10GetPersonRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32z\n\rPersonService\x12\x1d\n\x06GetAll\x12\x06.Empty\x1a\x0b.PersonList\x12!\n\x03Get\x12\x11.GetPersonRequest\x1a\x07.Person\x12\'\n\x06\x43reate\x12\x14.CreatePersonRequest\x1a\x07.Personb\x06proto3')



_PERSON = DESCRIPTOR.message_types_by_name['Person']
_PERSONLIST = DESCRIPTOR.message_types_by_name['PersonList']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_CREATEPERSONREQUEST = DESCRIPTOR.message_types_by_name['CreatePersonRequest']
_GETPERSONREQUEST = DESCRIPTOR.message_types_by_name['GetPersonRequest']
Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:Person)
  })
_sym_db.RegisterMessage(Person)

PersonList = _reflection.GeneratedProtocolMessageType('PersonList', (_message.Message,), {
  'DESCRIPTOR' : _PERSONLIST,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:PersonList)
  })
_sym_db.RegisterMessage(PersonList)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

CreatePersonRequest = _reflection.GeneratedProtocolMessageType('CreatePersonRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPERSONREQUEST,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:CreatePersonRequest)
  })
_sym_db.RegisterMessage(CreatePersonRequest)

GetPersonRequest = _reflection.GeneratedProtocolMessageType('GetPersonRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPERSONREQUEST,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:GetPersonRequest)
  })
_sym_db.RegisterMessage(GetPersonRequest)

_PERSONSERVICE = DESCRIPTOR.services_by_name['PersonService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSON._serialized_start=16
  _PERSON._serialized_end=97
  _PERSONLIST._serialized_start=99
  _PERSONLIST._serialized_end=135
  _EMPTY._serialized_start=137
  _EMPTY._serialized_end=144
  _CREATEPERSONREQUEST._serialized_start=146
  _CREATEPERSONREQUEST._serialized_end=228
  _GETPERSONREQUEST._serialized_start=230
  _GETPERSONREQUEST._serialized_end=260
  _PERSONSERVICE._serialized_start=262
  _PERSONSERVICE._serialized_end=384
# @@protoc_insertion_point(module_scope)
