apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api
  name: udaconnect-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30001
  selector:
    service: udaconnect-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api
  name: udaconnect-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-api
  template:
    metadata:
      labels:
        service: udaconnect-api
    spec:
      containers:
      - image: thinhtt84/nd064-udaconnect-api-gateway:latest
        name: udaconnect-api-gateway
        imagePullPolicy: Always
        env:
        - name: FLASK_ENV
          value: dev
        - name: CONNECTION_API_BASE_URL
          value: http://udaconnect-connection-api:5000/api
        - name: LOCATION_API_BASE_URL
          value: http://udaconnect-location-api:5000/api
        - name: PERSON_API_HOST
          value: udaconnect-person-api:50051
      restartPolicy: Always
